### ISSUE TITLE
lead_window end not respected in tc_gen config file

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/MET#1465] opened 2020-08-19 20:38 UTC
## Describe the Problem ##
I have lead_window configured such that beg = end = 48. When using the binary for #1427 for tc_gen, in the log file there are no lead times other than 48 reported. When using the binary for tc_gen in v9.1, I receive information about genesis events from the forecast data with lead times no shorter than 48 hours, but that exceed 48 hours. 

The total number of forecast and obs genesis events did not change, but why are there forecast lead times being reported outside of the lead_window I am requesting?

Did the bug fix in #1447 break something? Maybe #1448 will fix this?

Either way, this seems like a bug but what confuses me is that the total number of forecast genesis events is the same. Perhaps this indicates it's not a bug but the forecast lead/valid time being reported in the log is somehow out of sync or incorrect?

### Expected Behavior ###
I only expect to see genesis events reported from 48-h forecasts.

### Environment ###
Machine: kiowa
Config: /home/dadriaan/projects/gitissues/MET_1465/TCGenConfig_GDFlead48

### To Reproduce ###
Command1:
/d1/projects/MET/MET_pull_requests/met-9.1_beta3/bugfix_1427/MET-bugfix_1427_develop_tc_gen_into_develop/met/bin/tc_gen -track /home/dadriaan/projects/s2s/gdf/data/obs/bdecks/jtwc/ -track /home/dadriaan/projects/s2s/gdf/data/obs/bdecks/vigh/ -genesis /home/dadriaan/projects/s2s/gdf/data/fcst/tracker/reformat/* -config /home/dadriaan/projects/gitissues/MET_1465/TCGenConfig_GDFlead48 -out ./ALL48 -log ./met_log -v 5

Output: /home/dadriaan/projects/gitissues/MET_1465/Command1.log

Command2:
/usr/local/met-9.1/bin/tc_gen -track /home/dadriaan/projects/s2s/gdf/data/obs/bdecks/jtwc/ -track /home/dadriaan/projects/s2s/gdf/data/obs/bdecks/vigh/ -genesis /home/dadriaan/projects/s2s/gdf/data/fcst/tracker/reformat/* -config /home/dadriaan/projects/gitissues/MET_1465/TCGenConfig_GDFlead48 -out ./ALL48 -log ./met_log -v 5

Output: /home/dadriaan/projects/gitissues/MET_1465/Command2.log

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdb](https://github.com/dtcenter/METdb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name:  `bugfix_<Issue Number>_master_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>** and link the pull request to this issue.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch and link the pull request to this issue.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment] 2020-08-27 21:37
Since this is an apparent bug in met-9.1, I'm reassigning this to:
Project = METplus Version 3.1 Support
Milestone = MET 9.1.1 (bugfix)

**Comment by JohnHalleyGotway** [comment] 2020-10-20 21:21
I copied over sample input data from kiowa to my local machine and tested on the main_v9.1 branch. I was able to replicate this behavior.  When lead_window = { beg = 48; end = 48; }, I see lead times >= 48 in the log messages:
```
grep "initialization, " met_log  | awk '{print $6}' | sort -nu
48
54
60
66
72
78
84
```
Running the same command using tc_gen from the develop branch yields the same output. So this issue needs to be fixed in both main_v9.1 and develop.
Shifting to lead_window = { beg = 60; end = 60; } yields the following:
```
grep "initialization, " met_log  | awk '{print $6}' | sort -nu
60
66
72
78
84
90
96
102
108
```
So interestingly, the max - min lead times = 48 in both cases!

**Comment by JohnHalleyGotway** [comment] 2020-10-21 15:17
I strongly suspect that the issue is on this line:
https://github.com/dtcenter/MET/blob/f4240a73d3696432d35d1d8e0d5d9575312f893e/met/src/tools/tc_utils/tc_gen/tc_gen.cc#L561
We are checking and filtering by the lead time of the FIRST track point but not the lead time at which genesis occurred. So that's where the change to the logic is needed. We need a TrackInfo function to return something like:
   tracks[j].genesis_lead_time()

**Closed as completed** 2020-10-21 20:37 UTC
Labels: type: bug, priority: medium
