### ISSUE TITLE
Read in Tripolar Grids

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/MET#1231] opened 2020-01-09 17:30 UTC
MET needs the ability to handle tripolar grids. The NOAA EMC Real-Time Ocean Forecast System (RTOFS) uses a tripolar grid. Tripolar grids are 'a composite of two grids connected along a specified "join" latitude' and were originally defined by Murray 1996. More simply, there is a bipolar grid on one side (north or south) of the join latitude and a single pole grid on the other side. For RTOFS, this join latitude is 47°N. North of 47°N is an Arctic bipolar grid and south of 47°N is a Mercator projection (see attached figure). Tripiolar grids are designed to mitigate the convergence of longitudes at the North Pole.

**References:**
1. Environmental Modeling Center: "About Global RTOFS". https://polar.ncep.noaa.gov/global/about/
2. Geophysical Fluid Dynamics Laboratory: "A Guide to Grid Coupling in FMS". 
https://www.gfdl.noaa.gov/guide-to-grid-coupling-in-fms/
3. Murray, R. J., 1996: Explicit generation of orthogonal grids for ocean models. Journal of Computational 
Physics, 126, 251-273.

![rtofs_grid](https://user-images.githubusercontent.com/6549638/72092322-50985100-32cf-11ea-9ed6-5f6118db28ed.png)
RTOFS Model Grid

**Comment by lindsayrblank** [comment] 2020-01-22 18:06
RTOFS data is in netCDF format with CF conventions, according to their website.

**Comment by hsoh-u** [comment] 2020-12-01 22:04
Duplicate of #1345.
Tested
1. Download a file from  ftp://ftpprd.ncep.noaa.gov/pub/data/nccf/com/rtofs/prod/rtofs.20201201/rtofs_glo_2ds_f000_1hrly_diag.nc and ftp://ftpprd.ncep.noaa.gov/pub/data/nccf/com/rtofs/prod/rtofs.20201201/rtofs_glo_2ds_f012_1hrly_prog.nc
2. Run the command:
  - ./point2grid rtofs_glo_2ds_f000_1hrly_diag.nc G212 ice_coverage.nc -field 'name="ice_coverage"; level="(0,\*,\*)";' -v 4
  - /point2grid  rtofs_glo_2ds_f012_1hrly_prog.nc G212 sst.nc -field 'name="sst"; level="(0,\*,\*)";' -v 4

**Closed as completed by hsoh-u** 2020-12-01 22:04 UTC
Labels: requestor: NOAA/EMC, type: new feature, reporting: DTC NOAA R2O
