### ISSUE TITLE
Update documentation about parsing grid information from CF-compliant NetCDF files

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/MET#3009] opened 2024-11-06 02:48 UTC
## Describe the Task ##
This issue came up after discussion [2759](https://github.com/dtcenter/METplus/discussions/2759#discussioncomment-11126615).  The documentation describes how MET handles CF compliant netCDF files when there is no grid_mapping variable in the file.  However, rotated lat/lon grids seem to behave differently than regular lat/lon and require the standard name attribute to say grid_latitude and grid_longitude.  This issue is for updating the documentation to describe these differences for rotated lat/lon grids in how MET reads the files.  The documentation to update is in section 4.1.1

### Time Estimate ###
*Estimate the amount of work required here.*
A few hours to a day?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by CPKalb** [comment] 2024-11-06 02:49
@JohnHalleyGotway, we discussed this in the METplus meeting today

**Comment by jprestop** [comment] 2024-11-06 18:13
@JohnHalleyGotway and @CPKalb I assigned a project, cycle, milestone, and labels.  Please feel free to modify if they are inaccurate.  Who should this issue be assigned to? (Who knows this information best?)

**Comment by j-opatz** [comment] 2024-11-10 19:57
@JohnHalleyGotway I discussed this issue with @CPKalb on Friday. Her description of the issue is here:

> I'm guessing [this section](https://met.readthedocs.io/en/develop/Users_Guide/data_io.html#requirements-for-cf-compliant-netcdf) was written for regular lat/lon grids and not for rotated lat/lon grids.  I have not looked at the code to read in regular lat/lon grids, but, when I look at the [code](https://github.com/dtcenter/MET/blob/main_v11.1/src/libcode/vx_data2d_nccf/nccf_file.cc#L2624-L2722) for reading these rotated grids, I *think* it's doing the following:
> 1.  Looping through the dimensions of the file and looking for a variable that has the same name as a dimension
> 2.  If that variable is found, it checks to make sure the variable has a standard name attribute and that that attribute is not empty
> 3.  Checks to see if the standard name attribute is called either grid_latitude or grid_longitude
> 
> I think we should probably document that when a rotated lat/lon file does not have a grid_mapping variable, the lat/lon variables need to have standard names of grid_latitude and grid_longitude for them to be read in.

Is this a correct summation of the logic? If it is, Tina can draft up a fix for the documentation and get this completed before the rc1 cycle ends.

**Comment by JohnHalleyGotway** [comment] 2024-11-12 23:58
@CPKalb and @j-opatz, yes, you're looking in the right spot of the source code, and I don't have any way to improve your description. The only thing I'll note is that the NetCDF Climate-Forecast conventions are well-documented, and here's a link to the [Rotated Pole](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_rotated_pole) details. Where possible, I'd recommend linking to the CF-conventions documentation rather than restating it in the MET User's Guide. But it's up to you to decide the right mix of details here and link(s) to the CF info.

**Comment by CPKalb** [comment] 2024-11-14 17:02
@j-opatz would you be able to do the PR for this or should I see if someone else can do it?  I have a draft that should be ready shortly.

**Comment by j-opatz** [comment] 2024-11-14 17:10
@CPKalb I can take a look, sure. Slack me when it's ready and I'll review ASAP.

**Closed as completed** 2024-11-14 19:59 UTC
Labels: component: documentation, type: task, priority: medium, alert: NEED ACCOUNT KEY, requestor: NOAA/WPC
